#!/bin/sh

# put the shell file into /home/user/baseq3
# for load *.cfg, libraries and data.
# /usr/bin/ioquake3.arm "$*"

Q3A_BIN="/usr/bin/ioquake3.arm"
Q3A_SRV="/usr/bin/ioq3ded.arm"

echo "${Q3A_BIN} $*"
${Q3A_BIN} "$*"
